# Generated by Django 4.2.7 on 2026-02-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('matches_found', models.IntegerField(default=0)),
                ('videos_processed', models.IntegerField(default=0)),
                ('total_videos', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cameras', models.ManyToManyField(related_name='search_jobs', to='reports.camera')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_jobs', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
