# Generated by Django 4.2.7 on 2026-02-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CameraVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='camera_videos/')),
                ('recording_date', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recording_date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_person_name', models.CharField(max_length=200)),
                ('missing_person_photo', models.ImageField(upload_to='missing_persons/')),
                ('description', models.TextField()),
                ('last_seen_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('searching', 'Searching'), ('found', 'Found'), ('closed', 'Closed')], default='filed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_time', models.DateTimeField()),
                ('confidence', models.FloatField()),
                ('confidence_level', models.CharField(choices=[('high', 'High Confidence (>90%)'), ('medium', 'Medium Confidence (70-90%)'), ('low', 'Low Confidence (<70%)')], max_length=10)),
                ('face_snapshot', models.ImageField(upload_to='matched_faces/')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.camera')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='reports.report')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.cameravideo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
